// src/utils/permissions.js

export const ROLES = {
  TODOS: [
    "ADMINISTRADOR",
    "DIRETOR",
    "GERENTE",
    "COORDENADOR",
    "GESTOR",
    "TECNICO",
  ],
  GESTORES: ["ADMINISTRADOR", "DIRETOR", "GERENTE", "COORDENADOR", "GESTOR"],
  ADMIN_DIRETOR_GERENTE: ["ADMINISTRADOR", "DIRETOR", "GERENTE"],
  OPERACIONAIS: [
    "ADMINISTRADOR",
    "DIRETOR",
    "GERENTE",
    "COORDENADOR",
    "GESTOR",
    "TECNICO",
  ],
  ESTOQUE: ["ADMINISTRADOR", "DIRETOR", "GERENTE", "COORDENADOR", "GESTOR"],
  USUARIOS: ["ADMINISTRADOR", "DIRETOR"],
};
